### ISSUE TITLE
Host a version of the js code somewhere

### ISSUE THREAD

**Issue by erikdubbelboer** [poki/netlib#13]
Not every game uses a build flow that can handle an npm module. Some games require a simple script that they can either bundle with their game (PlayCanvas for example), or that they can include using a `<script>` tag.

**Comment by afrokick** [comment]
For development cases:
```
<script src="
https://cdn.jsdelivr.net/npm/@poki/netlib@0.0.10/dist/netlib.min.js
"></script>
```

**Comment by erikdubbelboer** [comment]
I think this should also work now:
```js
<script src="https://unpkg.com/@poki/netlib@0.0.12/dist/legacy.js"></script>
```
For engines like PlayCanvas it's better to download this file and include it into your game.
