### ISSUE TITLE
Private lobby is still public

### ISSUE THREAD

**Issue by aglitchman** [poki/netlib#49]
If you create a private lobby, netlib still makes its public. Look at https://github.com/poki/netlib/blob/fb566a26b9266323537c900ab235b7315bcf3379/internal/signaling/stores/postgres.go#L145

Plus, the `list()` function returns a list where all lobbies are private (public and non-public):

![image](https://github.com/poki/netlib/assets/193258/90dce32b-b197-431b-93d8-e2d868f7103e)

**Comment by koenbollen** [comment]
@aglitchman, hello again. This is correct, we have skipped it while developing. Should be an easy addition once we implement (basic) filters. 👍🏻

**Comment by koenbollen** [comment]
Hey @aglitchman,
Should get fixed by https://github.com/poki/netlib/pull/66
