### ISSUE TITLE
The lobby list function returns `null` if there are no public games

### ISSUE THREAD

**Issue by aglitchman** [poki/netlib#68]
The function `network.list()` returns `null` if there are no public games. 

I guess an empty array `[]` should be returned. 

If you create at least one public game, everything is ok.

**Comment by koenbollen** [comment]
Hey @aglitchman,
Thanks for reporting.
Agreed, we'll make a fix soon™. 👍🏻

**Comment by koenbollen** [comment]
@aglitchman This should now be resolved. And the fix was made in the backend, so it should now return an empty array without even updating. 👍🏻 Let me know if you find any more issues.
