### ISSUE TITLE
Impossible to query lobbies if you create a public lobby

### ISSUE THREAD

**Issue by aglitchman** [poki/netlib#82]
It seems that https://github.com/poki/netlib/pull/79 introduced a bug - it's impossible to query lobbies via `list()` if you create a **public** lobby:

```js
n.create({codeFormat: 'short', public: true})
```

Error is:
`"unable to handle packet: can't scan into dest[1]: cannot scan NULL into *int"`

![image](https://github.com/poki/netlib/assets/193258/83bbeb44-a493-4e27-981d-8c0529635664)

**Comment by erikdubbelboer** [comment]
I have created a fix, I'll release that as soon as the tests pass.

**Comment by aglitchman** [comment]
Many thanks! ❤️
